Xtendify/Simple-Calendar

- includes/events/event-builder.php
I've created a separate pull request for the less contentious commit from https://github.com/moonstonemedia/Simple-Calendar/pull/89
> Added spaces between attributes

- includes/post-types.php
Add `isset()` check before checking the globally registered post type.
> Closes #114

- includes/calendars/views/default-calendar-grid.php
- includes/calendars/views/default-calendar-list.php
- includes/events/event-builder.php
I've fixed some HTML5 validation errors
With the itemprop and content attribute changes I wasn't totally sure what I was doing, other than getting the validator to pass!
> Html validation

- readme.txt
Bumping "tested up to" version to 4.9.
> tested up to bump

- includes/calendars/views/default-calendar-list.php
Fixes color border issue for pro calendar when Calendar Settings > Google Calendar Pro > Limit Visible Events is set.
> fix duplicate style tag causing the issue

- assets/css/admin-add-calendar.min.css
- assets/css/admin.min.css
- assets/css/default-calendar-grid.min.css
- assets/css/default-calendar-list.min.css
- assets/js/admin-add-calendar.min.js
- assets/js/admin.min.js
- assets/js/default-calendar.min.js
- google-calendar-events.php
- includes/abstracts/calendar.php
- package.json
- readme.txt
Fixes sorting issue with events causing nav buttons to be disabled + grunt build.
> fix event sorting issue

- readme.txt
> update release date

- assets/css/admin-add-calendar.min.css
- assets/css/admin.min.css
- assets/css/default-calendar-grid.min.css
- assets/css/default-calendar-list.min.css
- assets/js/admin-add-calendar.min.js
- assets/js/admin.min.js
- assets/js/default-calendar.min.js
- google-calendar-events.php
- includes/main.php
- package.json
- readme.txt
Fix issue with settings not saving.
> fix issue with conditionsl preventing settings save

- composer.json
- composer.lock
- composer.third-party.dump-autoload
- scoper.inc.php
Solves https://github.com/Xtendify/Simple-Calendar/issues/382
> Add PHP polyfill

- assets/js/admin.js
- google-calendar-events.php
- includes/admin/ajax.php
- includes/admin/post-types.php
- package-lock.json
- package.json
- readme.txt
**Description:** Resolve vulnerability issue. reported on: https://patchstack.com/database/report-preview/591e2a4f-2471-475b-b0fe-0ec4183730ff
**Trello:** https://trello.com/c/WQEV0cK7
> vulnerability issue fix

- google-calendar-events.php
- includes/admin/ajax.php
- includes/admin/menus.php
- includes/admin/post-types.php
- package-lock.json
- package.json
- readme.txt
**Description:** As per the plugin Vulnerabilities suggestions I have added nonce and permission conditions on every admin ajax call.
Task: https://github.com/orgs/Xtendify/projects/2/views/1?pane=issue&itemId=27097785
> Vulnerability second part

- assets/css/admin-sett-style.css
- assets/css/tailwind-output-style.css
- includes/admin/pages.php
- includes/admin/pages/advanced.php
- includes/admin/pages/licenses.php
- includes/feeds/admin/google-admin.php
- includes/functions/admin-svg.php
- includes/functions/admin.php
- tailwind.config.js
i had added the prefix 'simcal-' to all the tailwind class.
> all tailwind class added the prefix

- contributing.md
- google-calendar-events.php
- package-lock.json
- package.json
- readme.md
- readme.txt
Description: Update version and changelog
> Changelog and version update

- includes/shortcodes.php
**Description:** Resolve shortcode conflict issue with unyson.
**Before**: https://nimb.ws/IEuWNP
After: https://www.screenpresso.com/=4Stuf
> Make compatible with unysone

- .bin/update-version.sh
- .bin/version-bump.sh
- google-calendar-events.php
- gruntfile.js
- package.json
- readme.txt
Now we do not need to change the version in all the files, just changing in package.json should be enough and it will update in zip during the build step
> Version change during build

- includes/admin/post-types.php
- package.json
- readme.txt
**Description:** Fixed the CSRF vulnerability for clear cache and clone calendar in admin. also fix for bulk clear cache action.
> Possible CSRF vulnerability

- assets/js/oauth-admin.js
- includes/admin/auth-service-actions.php
**Description:** Authentication and DeAuthentication process is done.
> De authenticaqtion work done

- includes/abstracts/calendar.php
- includes/admin/bulk-actions.php
- includes/admin/notices.php
- includes/feeds/google.php
- includes/functions/admin.php
- includes/update.php
**Description:** Add sanitize function every where we have add_query_arg as per suggestions to resolve the vulnerabilities.
Clickup: https://app.clickup.com/t/86cwk0caa
> Xss vulnarabilties fix

- includes/calendars/views/default-calendar-list.php
**Description:** I have updated the date format condition to rearrange the year position id the year is greater than the month. 
**Clickup:** https://app.clickup.com/t/86cwcyc4k
**Before:** https://gacharijohn.nimbusweb.me/share/8907398/srvn1qibqr57n3fkywwt
**After:** https://www.screenpresso.com/=gsegf
> Narrow width date issue

- includes/calendars/views/default-calendar-grid.php
**Description:** index issue after unchecking the print calendar option, added isset condition.
> Print caelndar index issue

- includes/feeds/google.php
- includes/main.php
- includes/oauthhelper/oauth-service-actions.php
- package.json
- readme.txt
**Description:** there was a event color issue which I have fixed by adding a default calendar color.
What i Did: https://www.screenpresso.com/=nKg1d
**Clickup:** https://app.clickup.com/t/86cvctmw1
**After:** https://www.screenpresso.com/=PzZFg
feedback: https://www.screenpresso.com/=Odlbe
> Event color not showing

- includes/feeds/google.php
- includes/functions/shared.php
- package.json
- readme.txt
Task - https://app.clickup.com/t/86cww6w76
> Fix compatibility warnings with PHP 8

- includes/feeds/google.php
- package.json
- readme.txt
https://wordpress.org/support/topic/update-not-showing-event-titles/
> Fix title and description not showing properly

- assets/css/default-calendar-grid.css
- assets/js/default-calendar.js
- includes/calendars/views/default-calendar-list.php
**Description:** Added print calendar button list view also. also maqke some changes in js becuase it was added display block to script tage when closing print screen and it added some content on bottom so I have added condition in it.
**Clickup:** https://app.clickup.com/t/86cwk3mex
**After:** https://www.screenpresso.com/=hPEJ8yLicPhk
> added print color option on list

- package.json
- readme.txt
**Description** version & changelog update for the multi day issue resolved by MartinixH
> version & changelog update
